export const ROUTES = {
  dashboard: '/',
  transactions: '/transactions',
  categories: '/categories',
  budgets: '/budgets',
  imports: '/imports',
  reports: '/reports',
  insights: '/insights',
  predictions: '/predictions',
  alerts: '/alerts',
  assistant: '/assistant',
  security: '/security',
  login: '/login',
  register: '/register',
  forgotPassword: '/forgot-password',
  resetPassword: '/reset-password',
} as const;
